### ISSUE TITLE
Group DM's for reminders

### ISSUE THREAD

**Issue by TheDataLeek** [PhasecoreX/PCXCogs#1]
The members of my server have requested that if other users are tagged in the contents of the `.remindme`, then when it comes time to send the reminder, the bot adds all tagged users (including the author) to a DM.

**Comment by PhasecoreX** [comment]
I'll have to look into if a bot can create and exist in a group DM in the first place. The way the code works currently is it directly sends a message to one user, which automatically creates a DM. I don't know if there is a way to have a bot manually create and add users to a group chat.

On top of that, another thing to think about is the potential for users to spam other users. A user could mention a bunch of people and notify all of them at once without their consent. A user could also end up in several reminder groups that they don't want to be in.

When using the remindme command itself, the user is opting into the bot sending them a message at a later time. If any user can have the bot send messages to other users unsolicited, that seems like it opens up the opportunity for abuse.

Over the weekend (hopefully) I'll look into the group DM thing. If that works, I'll have to think if there is a better way to have group reminders. Perhaps a reaction emoji added for others to join that reminder? I like that idea for duplicate reminders, but not group ones, as for groups you want to set who is allowed into the group.

**Comment by PhasecoreX** [comment]
After looking into this a bit, as far as I can tell, it looks like the bot cannot be in a group DM. Group DMs can only be created with friends, and since the bot cannot be friends with anyone, there would be no way to create a group DM with the bot in it.

For the moment, I will leave this issue open so that I can implement a "remind me too" functionality. That way, a user could create a reminder, and then anybody else could click an emoji to have the bot remind them as well at the same time (in separate DMs, of course).

**Comment by PhasecoreX** [comment]
Okay, it took a bit, but I have added the duplicate reminder functionality. If the bot is able to edit messages and add reactions, it will ask if anyone wants to also be reminded of whatever reminder was created. A user clicking the bell reaction will add the reminder for them. It doesn't solve making a group message, but maybe since each person is getting the reminder message at the same time, it would be a reminder to make one at that time.

**Comment by TheDataLeek** [comment]
Huge thanks for this! It's super cool and it's working great! Thanks for all your work.
