### ISSUE TITLE
[Remindme] Support mixed time units (e.g. 12h20m)

### ISSUE THREAD

**Issue by jack1142** [PhasecoreX/PCXCogs#11]
I would want to be able to do `[p]remindme 12h20m some reminder` to set up reminder that will happen in 12 hours and 20 minutes. Iirc, Red's core offers a utility converter for that kind of times so you might be able to use it (`TimedeltaConverter`)

**Comment by PhasecoreX** [comment]
Thanks for pointing this out! It looks very cool. I will implement it soon.

**Comment by PhasecoreX** [comment]
This should be working now with 5b202f9. Update the cog and let me know if there's any issues!

**Comment by jack1142** [comment]
Haven't tested this yet, but just in case you didn't know, there is also a `TimedeltaConverter`, not just `parse_timedelta`, I'm not sure if you just preferred `parse_timedelta` or didn't know about the converter so mentioning just in case 😄

**Comment by PhasecoreX** [comment]
I considered it, but the problem is with legacy support. If the user wants to, they can still use the `[p]remindme 4 hours ...` format, as it was in the V2 days. If the time argument is not a valid timedelta (just a number 4 in this case), I take the first word of their text argument, append it to the first argument, and remove it from the text argument.

I considered having a `TimedeltaConverter` have a `default_unit` of the first word of the text argument, but I couldn't find a way of doing that as well as removing that first word from the text if it needed to be used.

**Comment by jack1142** [comment]
Oh, yeah I actually was thinking that you should probably keep the legacy support, I just didn't notice you actually did.
If `parse_timedelta` made it possible, then it was totally worth it, thanks for the explanation 👍
