### ISSUE TITLE
[FEATURE REQUEST] AutoRoom Channels

### ISSUE THREAD

**Issue by JustKilian** [PhasecoreX/PCXCogs#115]
I know with the last python update, the channel side chats got added. But because we had more fun using the normal chats that got created when joining a voice chat, I wanted to ask if you could add it back in. I also thought about doing it myself and creating a PR, but didn't know if you are ok with it.

Best

JustKilian

**Comment by PhasecoreX** [comment]
Actually, the switch to using the text channels in voice channels happened almost a year ago now. I am not going to add the regular text channels back in. Using the built in text/voice channels makes the code much easier to maintain, since the separate text channel thing was more or less a hack and hard to manage.

I am curious though, what makes the normal text channels more fun? Also, what is it that you are missing from the normal text channels that aren't in the text/voice channels?

**Comment by ocformula** [comment]
Discord's built in text/voice channels are very inconvenient.
I've actually seen very few people use them.
People don't realize what's going on and what conversations are taking place in the built in text/voice channels.
And the interface is pretty terrible. Discord's built in text/voice channels obscure the member list on the server and make the screen very distracting.
No one ends up using that feature, and even if they do, it's not interesting to people because non-members who enter the temporary channel can eavesdrop on the conversation.

For Discord users, the normal text channels that are created separately are more intuitive, convenient, and fun.
It's interesting that many people are chatting in the voice channel, and the content of the conversation on the normal text channels can't be seen from the outside, and it seems to have the effect of increasing the participation rate in Discord.


At least not yet, Discord's built-in text/voice channels are so clunky and inconvenient that it's premature to replace them with THE NORMAL TEXT CHANNELS.

I've seen other servers using the https://astro-bot.space/ bot, which still supports the normal text channels, and everyone uses it.

**Comment by ocformula** [comment]
> Actually, the switch to using the text channels in voice channels happened almost a year ago now. I am not going to add the regular text channels back in. Using the built in text/voice channels makes the code much easier to maintain, since the separate text channel thing was more or less a hack and hard to manage.
> 
> I am curious though, what makes the normal text channels more fun? Also, what is it that you are missing from the normal text channels that aren't in the text/voice channels?

Discord's built in text/voice channels are very inconvenient.
I've actually seen very few people use them.
People don't realize what's going on and what conversations are taking place in the built in text/voice channels.
And the interface is pretty terrible. Discord's built in text/voice channels obscure the member list on the server and make the screen very distracting.
No one ends up using that feature, and even if they do, it's not interesting to people because non-members who enter the temporary channel can eavesdrop on the conversation.

For Discord users, the normal text channels that are created separately are more intuitive, convenient, and fun.
It's interesting that many people are chatting in the voice channel, and the content of the conversation on the normal text channels can't be seen from the outside, and it seems to have the effect of increasing the participation rate in Discord.


At least not yet, Discord's built-in text/voice channels are so clunky and inconvenient that it's premature to replace them with THE NORMAL TEXT CHANNELS.

I've seen other servers using the https://astro-bot.space/ bot, which still supports the normal text channels, and everyone uses it.

**Comment by ocformula** [comment]
> I know with the last python update, the channel side chats got added. But because we had more fun using the normal chats that got created when joining a voice chat, I wanted to ask if you could add it back in. I also thought about doing it myself and creating a PR, but didn't know if you are ok with it.
> 
> Best
> 
> JustKilian

I cloned and modified the previous code in this repository to use AutoRoom with the normal text channel.
https://github.com/ocformula/OCFCogs

**Comment by JustKilian** [comment]
In my opinion, the best solution would be to add it back in and let the users decide if an autoroom chat is being created for a channel or not. Like with the channel name.

**Comment by JustKilian** [comment]
@PhasecoreX can we convince you to add that feature back in as an optional feature? Noone has to use it but if people want to they would have the possibility.

**Comment by PhasecoreX** [comment]
I guess I can look into adding it back at some point. It's low priority for now because of real life stuff going on, and lately when I do get a bit of spare time, there's a different project I'm more heavily working on now. Comes and goes in waves, what I am interested in working on at any one point.

**Comment by PhasecoreX** [comment]
Alright I got around to re-adding the text channel thing back. You can enable it with `[p]autoroomset modify legacytextchannel enable <channel_name>`. I did a bit of testing, should work fine, but if it doesn't then let me know.

**Comment by JustKilian** [comment]
You’re a Hero Thanks a lot. I will try it.

PhasecoreX ***@***.***> schrieb am Di. 17. Okt. 2023 um 00:03:
