### ISSUE TITLE
Adding AlertBot as a service

### ISSUE THREAD

**Issue by MadamJazzy** [PhasecoreX/PCXCogs#12]
It would be awesome if AlertBot could be added as a service for the bancheck cog. I can even supply the coding for the actual check so that you don't have to go through the trouble of having to figure out how their api works and code it yourself. If you decide to include it a couple notes: 

Alertbot has a default api limit of 1 request per second and 1000 requests per day(resets at midnight EST), to work around this the code includes tokens as a list and includes a while statement to check if a 200 response is given and if not will automatically cycle to the next token in the list.

Of course your cog uses a different method of handling the data and embed so of course that may need to be "tweaked" to your liking and to work with your embed creation and your lookup_result.py. But figured it couldn't hurt to request it. 

```python
async def ablookup(self, member):
	URL = "https://api.alertbot.services/v1/?action=bancheck&userid={}".format(member.id)
	#tokens needs to be set as a list so multiple tokens can be added since alertbot only allows 1000 requests per day per token
	tokens = []
	x = 0
	#uses while statement to cycle through tokens for when daily requests have been reached
	while x < len(tokens):
        header = {"AuthKey": tokens[x]}
        resp = await self.bot.session.get(url, headers=header)
        if resp.status == 200:
            resp = await resp.json()
            resp["data"]["result"] = result
            ava = member.avatar_url
            if result["banned"]:
                title = f"Ban Found for {member}!"
                reason = result["reason"]
                date = result["date"]
                proof = result["proof"]
                desc = f"UserID: {member.id}\nReason: {reason}\nDate: {date}\nProof URL: {proof}\n"
                color = discord.Color.red()
            else:
                title = f"No ban found for {member}"
                color = discord.Color.Green()
                desc = f"UserID: {member.id}"
            return (ava, desc, color, title)
        x += 1
    False
    ```

**Comment by PhasecoreX** [comment]
Thank you for bringing this service to my attention! I will be sure to add it!

At one point, API keys were defined per guild (or not at all, in the case of discord.services). Once KSoft came around, it was clear that the key was specifically for the bot, not a key per guild the bot was in (this had to do with the bot approval process). At the moment, I'm not sure of Globans stance, but clearly for Alertbot it should be an API key per guild the bot is in. This will require rewriting a bit more to support both global API keys as well as per server API keys.

As for defining multiple keys per service, seems kinda like it would be against Alertbots TOS (if they had one). For now, it's not a priority to implement, since hopefully 1000 new user lookups per day per server will be enough. If not, there's always the other supported services to pick up the slack, as well as a potentially paid option for Alertbot(?) (I only say this because they mention it's a free api key, as opposed to just an api key).

Also, no other service currently supported has a rate limit either (KSoft has one that's like 20 a second or something crazy). I'll have to also implement something to handle rate limiting, but not to slow down checks on a huge influx of users raiding a server. I'll have to think about that one.

**Comment by MadamJazzy** [comment]
Yea I'm actually the owner of discord.services and that service is down right now but is actively being rebuilt and I wont ever have the api keys if I can help it. With alertbot it's a per token limit and yes they have a higher limit if u donate.
________________________________

**Comment by PhasecoreX** [comment]
Okay, with 62fdf64 I have completely rewrote BanCheck in order to support per guild and per bot API keys. This was a much needed rewrite, and I'm quite proud of it (especially `[p]bancheckset`). Also, Alertbot is now supported, so go try it out! (`[p]bancheckset service api alertbot API_KEY`, then `[p]bancheckset service enable alertbot`) Let me know if I accidentally broke something.

I look forward to when discord.services comes back! At that point, I can easily add it to the list of supported ban checking services.
