### ISSUE TITLE
[Ban check] Suggestion: bancheck report

### ISSUE THREAD

**Issue by Brandjuh** [PhasecoreX/PCXCogs#13]
I would like to see a option to report users to ksoft.si api with a seperate command. I am not sure if that is possible, I report them now via there bot in there server. 

My idea was like this: Add a image as proof and [p]bancheck report <USERID> <MSG>
![image](https://user-images.githubusercontent.com/26203955/73140653-9d27ae80-407b-11ea-8d0b-e8a70bdb5d14.png)

I hope you will get my idea. You can always hit me up on discord `Brandjuh#0001`. I am also in red server aswell in cog server.

**Comment by PhasecoreX** [comment]
Yes, this does make sense, and their api does have an add ban endpoint. Is this the format (comment on an image) that the official bot uses? Also did you need any permissions in order to report people? I worry because a bot could be in several servers, and the api key is global. You wouldn't want a random person in a server spamming the report command, perhaps getting the entire api key banned or something. Or perhaps they've already thought of this? There's a bit of research to do on this.

There's also going to have to be some checks to make sure the comment command is actually on a picture in the first place, and I'll have to find out whether or not a discord image link (instead of an imgur one) is allowed as proof.

**Comment by Brandjuh** [comment]
**Is this the format (comment on an image) that the official bot uses?** 
Reporting users in there own server looks like the following 
![image](https://user-images.githubusercontent.com/26203955/73268851-fa3a7600-41db-11ea-9f6c-80c83441c0d6.png)

**Also did you need any permissions in order to report people?**
I am not sure, I have a user role because my bot. Not sure if non users can use that command. 

For me I am fine if the command is botowner since its my API.

**Comment by PhasecoreX** [comment]
Okay! It took a while, but I finally got it done. Two new commands are now included:

- `[p]banreport <member> <ban_message>`: Use this command as the comment on a ban proof image upload. The image will be uploaded anonymously to Imgur (it requires Imgur credentials), as Discord media doesn't stick around when you delete it.
- `[p]banreport <member> <image_proof_url> <ban_message>`: Use this command if you already uploaded an image to an image host.

At the moment these commands will only interface with KSoft.Si, and can only be run by the bot owner. In the future I can set it up to send ban reports to other services, as well as allow it to be used by others (admins?)

Full disclosure, I have not tested this completely. I have tested everything except the actual sending of the reports (as I don't have anyone to ban). But I have mocked the responses and verified that the results display works correctly. If you can test that out with your next member(s) to ban, I would highly appreciate it!

I will close this for now, but I get all notifications so please don't hesitate to let me know if anything needs fixing.

**Comment by Brandjuh** [comment]
Sorry for reopening.
Thanks for adding but can you make it possible to report with ID? Most of the times users get banned first then reported, sadly thats impossible with mention only. <@!ID> doenst work.

**Comment by PhasecoreX** [comment]
No worries! I have updated this so you should be able to use either a user ID or a user mention for both lookups and reports! Let me know if there's anything I missed.
