### ISSUE TITLE
[RemindMe] `[p]reminder list` could show reminder time

### ISSUE THREAD

**Issue by jack1142** [PhasecoreX/PCXCogs#17]
I think it would be nice if `[p]reminder list` would either show the time *until* reminder gets sent or the time *when* it will be sent

**Comment by PhasecoreX** [comment]
I think "until" would be easy to do now (with humanize timedelta), but I think "when" is kinda weird with time zones and whatnot. Unless there's now a way to know the users time zone? There wasn't at the time I wrote it, as far as I could tell.

I'll do the "until" portion since that'll be easy. And I can add the "when" part later if it's possible.

**Comment by jack1142** [comment]
> Unless there's now a way to know the users time zone?

You're right, there's not. I didn't consider it 😄 Either of these work for me so thanks :)

**Comment by PhasecoreX** [comment]
8ff684d adds a time until reminder display, as well as makes the list itself look nicer. Thanks for the suggestion!
