### ISSUE TITLE
autoroom VC sound quality

### ISSUE THREAD

**Issue by SteZZz** [PhasecoreX/PCXCogs#27]
the default of 64kbit is being used right now.
it would preferably be the highest possible value or the value from the auto room channel that it was created from.

**Comment by SteZZz** [comment]
@PhasecoreX

**Comment by PhasecoreX** [comment]
I'm planning on adding more settings that you can configure for each AutoRoom Source, one of which is the default bitrate of created AutoRooms.

**Comment by PhasecoreX** [comment]
With 1bedb61, this should now be configurable. In your case, you want your AutoRooms to have the highest bitrate supported by the guild, so you can use the command `.autoroomset modify bitrate <autoroom_source_channel> max`

Instead of `max`, you can also set a specific bitrate (in kilobits), or `default` to use Discords default (64kbps at the time).

Enjoy!
