### ISSUE TITLE
Changelog in UpdateNotify

### ISSUE THREAD

**Issue by Sandvich** [PhasecoreX/PCXCogs#32]
There have been a fair few updates lately, and checking exactly what those updates are tends to be an annoying process since I'm not building the image from git, but rather pulling from Docker Hub.

It'd be useful to have a simple changelog type message in UpdateNotify that either explains the update or maybe just pulls the last few commit comments from git.

Also, thank you for your work on both the docker image and these cogs, they've been super useful!

**Comment by PhasecoreX** [comment]
You're welcome! Glad you're enjoying the image and the cogs!

I have been researching this for a while now and I had a whole essay ready to send and close this issue, with reasons why I couldn't do this with the current API's I have free access to and the clunky way I was forced to use them to check for updates. But, I just figured out that I can most likely use the API for the GitHub Actions to accomplish this and also make the UpdateNotify notifications more accurate. I will look into this.

Also, if it makes you feel better, the only reason updates were happening as of recently is because I was moving the build over to GitHub Actions. The last meaningful functional update was on July 5th, almost 5 months ago.

**Comment by Sandvich** [comment]
That sounds great, looking forward to seeing that working :)
And that makes sense - a friend of mine switched to github actions recently and he said it was very difficult to get right...

**Comment by PhasecoreX** [comment]
Okay with df0ba12 I have switched over the checking logic to use the GitHub Actions results. This will now show the commit message that is associated with the most recent build (and thus the images on Docker Hub/GHCR), in addition to being more accurate and simpler code (only one API call!)

One difference now is that any base image updates that cause the image to rebuild will also show up as an update (they didn't before). The user may want to know about these (for potential base image security updates) or not (for less notifications), so they can use `[p]updatenotify docker type` to toggle being notified about these.

Enjoy! And let me know if I missed something.

**Comment by Sandvich** [comment]
I saw the log when it poked me to update today :D
I had actually completely forgotten about this until I saw that log, which is probably a good sign! When you don't need to think about a project like this it's generally doing its job well!

**Comment by PhasecoreX** [comment]
Hey that's good! Yes, I like when my software silently does it's job!
