### ISSUE TITLE
[AutoRoom] Change name of Voice/Text Channels

### ISSUE THREAD

**Issue by nino-salih** [PhasecoreX/PCXCogs#33]
Hi, 
Id would be cool to have the option/command to change the name generation of the automatic created Voice/Text channels with a template with fields like: 

- {count} could be helpful for public voice channels like [1] public room, [2] public room
- {name} the user name
- {access} is the channel private or public as an indicator. Could be a 🔒 and 🔓 emote or a user can change it to his linking

An example would be:
{access} {name}'s Room
🔒 John's Room

On a related note: the automatically generated text channels only have the name: autoroom-text-channel is that a bug or desired behaviour?

**Comment by PhasecoreX** [comment]
So, `{count}` doesn't make sense to me, as there's no inherent order to the rooms. `[1] public room` and `[2] public room` could be created, and then the first one empties and is removed, leaving just `[2] public room`. Does the next room become 1 or 3?

1 would be out of order (new channels go to the bottom):
```
[2] public room
[1] public room
```
Plus then we would need to keep track of which numbers are being used. Can't read all of the current AutoRoom names because the AutoRoom owner could rename them.

3 just seems like useless counting (do we just keep counting up forever?):
```
[2] public room
[3] public room
```
Plus, users might be confused on where room 1 went.

`{access}` also seems not very useful to me, because if a user isn't allowed to access a channel, they aren't able to even see it. And in regards to indicating private/public, the AutoRoom owner can switch the type of channel (private or public) at any time, making the `{access}` emoji incorrect. They can also rename the channel and put whatever emoji they want, or remove it entirely.

That leaves us with `{name}`, which we already have. I wouldn't be opposed to adding a sort of template system, but I don't know of any useful template values. Keep in mind channel names can't be too long, and also the AutoRoom owner can just rename them anyway.

In regards to "autoroom-text-channel", it is desired behavior, since a normal user (anyone that isn't the guild owner) will only ever see one of these AutoRoom text channels at a time. Plus, the names are only allowed to be lowercase and hyphens, so I didn't want to deal with converting AutoRoom names over to text channel names, and also didn't want to deal with syncing changes between the voice channel and the text channel names.

**Comment by nino-salih** [comment]
Yeah you right about the {counter} that would be a syncing nightmare. So yeah not a good idea

Same with {access}.

Also true with the {name} field. 

The only useful thing I can think of with a {name} field would be too use translations of the world room in other languages and that could also be implemented with translations for the cog and not a template. 

You can close the issue I can't think of useful fields. 

But thank you for your thoughts on the matter

**Comment by PhasecoreX** [comment]
So I sort of implemented the counter thing, but automatic. When the AutoRoom name is generated (any format), it checks what the other AutoRoom names are and will append a " (2)" if it already exists. If that exists, it tries a " (3)" instead, then " (4)", etc.

Also, since we now have unique AutoRoom names, I went ahead and made the text channel name try to match it, instead of being "autoroom-text-channel". It's not perfect, as there isn't much you can do with just lowercase letters, numbers, and hyphens lol. But, it should help the guild owner in that they don't need so sift through a bunch of the same named channels.

I'll close this now, hopefully this update helps you out a bit!
