### ISSUE TITLE
AutoRoom - Disable users modifying generated rooms

### ISSUE THREAD

**Issue by Jademalo** [PhasecoreX/PCXCogs#35]
Is it possible to disable a user from modifying a room they have generated automatically?

It seems that when a room is created, the user that created it is given a certain set of permissions. Ideally I'd like to be able to disallow this, so the channel functions like a basic unmodifiable channel for the duration of it's existance.

**Comment by PhasecoreX** [comment]
I figured this feature would be requested at some point haha. The initial idea of AutoRoom was to allow the users to make their own rooms, do whatever they want without bothering others, and then when done it's all cleaned up.

It should be easy to lock down the room name/bitrate/user limit editing, as that is just a permission. Maybe the server admins want to keep their AutoRooms the same user limit, or keep them all with the name "Table #". That makes sense. What I am wondering though is about allowing the AutoRoom Owner to switch their room between public and private, and allowing them to allow/deny users into their room.

I think regardless the AutoRoom Owner should always have allow/deny permissions. When you remove those permissions, private AutoRooms become useless (they can't allow anyone in), and public AutoRooms could become annoying if you have a user that insists on following you into every AutoRoom you try and create in order to avoid them (also causes API spam, creating and deleting rooms over and over).

For the public/private switching, I'll have to think about it. I don't really want to have it be a separate lock option from room name/bitrate/user limit, as that makes things more complicated. So it's either tied to being locked when the room name/bitrate/user limit are locked, or it can always be switched.

I keep writing and rewriting this response as I keep thinking of more ideas to solve this or other roadblocks I will run into. Point is, I'll get some sort of settings in there to lock stuff down.

**Comment by Jademalo** [comment]
Awesome, thank you for considering this!

This is probably just a classic case of different people having different use cases, in terms of complexity. From my perspective for our needs, we basically want end users to have *zero* control over any actual parameters of the channels, and all rooms to always be public. Based on what you're saying, your approach seems to be that you see the person who generates the room as "owning" the room. What I'm really suggesting is an option where the room isn't to be "owned" by the person who created it, it's purely a mechanism to have a dynamic number of separate voice channels available without cluttering up the channel list in the discord if nobody is online.

For our server, we have a lobby room, which if you join generates an additional room. We want this generated room to always be open and accessible to everyone, so people are free to come and watch and listen as they please. Once everyone leaves the room, it gets deleted.
No complexity, no bitrate changes, no moving, no renaming, no private rooms. 

After thinking about what you were saying, the best approach I can come up with personally would be to have three room types - Public, Personal, and Private. 
- Public just generates the room with no special or personal permissions, perhaps copying the permissions structure of the base autoroom.
- Personal works like Public does now, generating a room where the person who generated the room has additional permissions and management options. 
- Private works like it does now, generating a private room that only that user can see, with the ability to move people into that room.

That seems like the most elegant solution to me, without adding in extra complexity in terms of configurable granular permissions.

**Comment by luxus** [comment]
Hello,
At the moment I use autovoicechannel and i like the Channel Template Part 
https://wiki.dotsbots.com/en/commands/template
maybe it gives you some ideas what could be options for generated channel names,
Because I think not many will figure out that they can change the name it themselves

**Comment by PhasecoreX** [comment]
Apologies for the delay, but with 130cf25 this should be solved. I have added a `server` type of AutoRoom, where it's just like the `public` AutoRoom type but with no AutoRoom Owner (so no settings can be changed). You can set an AutoRoom Source to generate server AutoRooms by using `[p]autoroomset modify type server <autoroom_source>`

**Comment by Jademalo** [comment]
Awesome, this works perfectly.
Thank you so much, it's hugely appreciated!
