### ISSUE TITLE
AutoRoom - Sequential naming from specified string

### ISSUE THREAD

**Issue by Jademalo** [PhasecoreX/PCXCogs#36]
At present, the only options for room names are `game` or `name`, which generates a room based on either the game you're playing or your discord name.

Ideally, I'd like to have the generated rooms use a sequential numbered list, based on a predefined name. 
For example, if the predefined name was `Table`, then the first room generated would be `Table 1`, the second `Table 2`, etc. This would allow for cleaner organisation, and be a lot clearer to the users.

Thanks!

**Comment by PhasecoreX** [comment]
So I can add custom name template support (I figured I would have to at some point), it'll just take a bit to figure out a clean way of doing it.

As for the numbering, there already is a system in place that detects if a room name is already taken and will append " (2)" to the end of it, and keep increasing the number until it's available:

- Table
- Table (2)
- Table (3)

As you can see, it doesn't start with "Table (1)", and it always has the numbers in parenthesis. I'll have to think this over as well, maybe have some sort of a format-able suffix? Is it worth the effort? Too complex? Not sure yet.

Regardless, I'll see about making a custom name template.

**Comment by Jademalo** [comment]
Awesome, thanks for looking at this!

My personal use case is that we basically have a lobby room, and then after joining you're sent to a separate "Table" room for you and your opponent. Having automatic sequential numbering would be useful, purely for an aesthetic organisational setup. We sometimes have 3-4 tables at once. It would definitely be nice to have formatable suffixes, though if it's an extreme amount of work then it's nowhere near as important as simply being able to name them.

In addition, it might be nice to have an option to use the name of the lobby room to generate subsequent rooms. I wouldn't use it personally, but it seems like it wouldn't be too much trouble if you've already got custom names implemented anyway, and I expect it would be a useful part of the feature set for other users.

I do also want to say - I'm really impressed with the stability of this cog. It's quick, responsive, and doesn't seem to leave ghost channels like some other options we tried. 

Thanks!

**Comment by PhasecoreX** [comment]
I'm glad you're enjoying the cog so far! I put a lot of work into it to make sure it's as easy to use and foolproof as possible, while still being very customizable!

With 8ab911a, this should be complete. Check out `[p]autoroomset modify name custom` to set a custom room name template for an AutoRoom Source, and then check out `[p]autoroomset modify increment` to set up the custom incrementing bit of the channel name.

For your use case, these command should get you what you want:
- `[p]autoroomset modify name custom <autoroom_source> Table`
  - Channel names will always be "Table"
- `[p]autoroomset modify increment custom <autoroom_source> {number}`
  - Duplicate channel names (since they're all "Table") will have just a number appended to them (no parenthesis like default)
- `[p]autoroomset modify increment always <autoroom_source>`
  - The first room will have " 1" appended to it as well

Your rooms will look like this:
- `Table 1`
- `Table 2`
- `Table 3`
etc.

Enjoy!

**Comment by Jademalo** [comment]
Oh wow, this works absolutely perfectly!

This is really nicely implemented, I love how customisable and clear it is.
Thank you so much for implementing this, I'm extremely impressed by this and genuinely cannot thank you enough!
