### ISSUE TITLE
[Autoroom] Permission issue with message history

### ISSUE THREAD

**Issue by Zenchaeus** [PhasecoreX/PCXCogs#44]
Can you help me? When a member creates an autoroom, they don't seem to have the 'read message history' permission for them. I already made sure that the permission is enabled for the category but it still doesn't work. Am I missing something?

![image](https://user-images.githubusercontent.com/67543490/114403500-6f267f80-9bd7-11eb-81f5-d31e8e923127.png)

**Comment by Zenchaeus** [comment]
> So I assume this is the optional text channel that an AutoRoom can create. I don't copy over any extra permissions from anywhere for those, so they should just work. I would check the users roles, see if there's something there that's blocking it, and then the category (which you say you already checked).
> 
> The permissions that should be on the generated text channel are denied read permissions for everyone, and then all users in the voice channel have read permissions. Nothing should be denying history as far as I know...

it seems adding the 'read message history' permission for the roles in server settings (server-wide) fixes it. but my problem is that i control the permission on a category and channel wise while all permission for roles in server settings are all disabled.

**Comment by PhasecoreX** [comment]
Permissions never work exactly how I would expect them to. I would assume that if a permission isn't set on a channel, it would then check the category if it exists, and then check the roles/server. But I guess it doesn't? I'll have to do some testing on this.

**Comment by Zenchaeus** [comment]
> Permissions never work exactly how I would expect them to. I would assume that if a permission isn't set on a channel, it would then check the category if it exists, and then check the roles/server. But I guess it doesn't? I'll have to do some testing on this.

for my case, i tried disabling the permissions for the category and also the channel and just set the 'read message history' permission server wide and it works just fine. but if i set it on the category or the channel, it doesn't work.

**Comment by PhasecoreX** [comment]
With 63ca9fd I have made it so that the Read Message History permission is copied over to the resulting AutoRoom Text Channel when created. Now it doesn't matter if the server has it disabled for the everyone role, as long as the bot has the Read Message History permission either on one of it's roles or on the destination category, it'll set it to allowed for everyone who can view the text channel.

In the future there will be threads, which could lend to more granular permissions like we have for the voice channels. But this should be a stop-gap for the time being.
