### ISSUE TITLE
[remindme] Use discord's new native timestamps

### ISSUE THREAD

**Issue by maxbooiii** [PhasecoreX/PCXCogs#53]
Hello, i was thinking of if the new native discord timestamps could be used after a reminder has been added. 

Example:
`I will remind you of that <t:1632597245:R>`  
post `<t:1632597245:R>` in a discord chat. you can find examples from [here](https://whatismyti.me/#/discordtimestamps).

**Comment by PhasecoreX** [comment]
Yes, I already have that on my radar to implement.

**Comment by maxbooiii** [comment]
> Yes, I already have that on my radar to implement.

Ah cool. 👍

**Comment by PhasecoreX** [comment]
With b51473a, I have added timestamps.

Due to how the underlying reminder data is stored, there are certain spots that are not possible to add a timestamp (specifically ones that rely on when a reminder was created, in the past). But if I did miss a spot (a spot that says something like "In 3 days...") then let me know!

**Comment by maxbooiii** [comment]
I see, Thank you.
