### ISSUE TITLE
[Feature Request - RemindMe] Ability to remind others?

### ISSUE THREAD

**Issue by Dalarialus** [PhasecoreX/PCXCogs#58]
Would it be possible to have a RemindMe reminder target someone else? I.E. `!remind @anotheruser in 5 minutes MESSAGE`?

This is a feature available in Ub3rbot and I'd love to be able to do it with Red :)

**Comment by PhasecoreX** [comment]
The issue I have with reminding others is that many users don't want unsolicited reminders sent to them. A "remind others" feature would give users the ability to make the bot "talk" to other users on their behalf. Imagine someone loading up all 20 (default limit) of their reminders to all go off at roughly the same time directed at some other users DMs. Then you get complaints on your bot, since it's randomly DM-ing people for no reason.

Maybe the IRC origins of Ub3rbot are why they do that. But I know for Discord, many people don't even like being pinged, let alone DM'ed without a good reason. Thus, I will close this feature request. If you have a really good use case for reminding others, please let me know. Otherwise, I feel like you could just make a reminder for yourself to go contact that other person.
