### ISSUE TITLE
[BanCheck] Suggestion

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [PhasecoreX/PCXCogs#6]
For BanCheck I suggest making the enableservice commands set the API as a global and not guild in config, as to get a Token, you need to have the bots Client ID and it needs to be approved before you get the token, so only the owner should be able to set it. I also suggest having a command that gives you the links that take you straight to where you sign up to get a API key.

**Comment by Ianardo-DiCaprio** [comment]
I have a PR for making the enable/disable service commands global if you want it.

**Comment by PhasecoreX** [comment]
My initial thoughts were that it should be a separate token per server, as a server owner could or could not have permission to use a specific service in his server. But then I forgot (and you have reminded me), that at least for KSoft.Si, each bot gets its own token, so it is not possible to have more than one token per bot (even if they are used exclusively in different servers).

I see your commits, and I will cherry pick them along with some other changes, an important one being that only the owner can see and execute these service enable/disable commands. I have a couple of other changes that I need to think about too, such as:

- If a server wants to only use one service instead of all enabled ones.
- If a service only allows one per server, as opposed to one per bot (not sure how they would check this though).
- Need to somehow move the currently set up services in the guild settings into the global settings. Not sure if this is possible?
- I also need to consider rate limiting across all servers the bot is in, but that can be for another time.

**Comment by PhasecoreX** [comment]
Okay I have moved the guild service settings into the global settings. Based on the fact that the Imgur and YouTube API keys are also for the entire bot in all servers, I'm just going to leave all of the ban checking services as bot global as well, until someone makes a compelling argument to having per-server service selection.

I'll also look into adding the links for signing up. I need to see how I can cleanly add that.

**Comment by Ianardo-DiCaprio** [comment]
Could show the link when `[p]bancheck enableservice` is used without the service or key.

**Comment by PhasecoreX** [comment]
With the latest commit, I have revamped the menu a bit, which includes some fancy embeds to show the service links. You can find this when doing `.bancheckset service`.

With that, this issue should now be done! Thanks!
