### ISSUE TITLE
[Autoroom] bot role configuration

### ISSUE THREAD

**Issue by hirata-estate** [PhasecoreX/PCXCogs#67]
I want to make bots be usable in autorooms, but the bot seems to deny perms for connecting and viewing the channels even if both the autoroom source and category has them. Doing !autoroom allow <bot_role> also isn't doable, since they have to join the voice channel in the first place.

The only alternative would be adding the administrator permission to every single bot, which is heavily unfavored.

**Comment by ultraic-space** [comment]
Changed the title & suggestion:
Make a bot role that has access to all autoroom voice and text channels by default. (toggle-able by user by doing !autoroom bots)
When only bot roles are left in the voice channel, disconnect the bots and delete the voice & text channel

**Comment by PhasecoreX** [comment]
To clarify, you mean usable in the AutoRoom Text Channel, right? Cause the bot can join the created voice channel based on if it can join the AutoRoom Source it was made from. But you're right, only the ones that are in the voice channel (or admins/mods, if set up) can see the text channel.

Your suggestion seems reasonable. Allow usage of bots in text channels if the user wants them. I'll have to think about how to actually implement that though...

**Comment by PhasecoreX** [comment]
Sorry it's been a while, but since Discord added the text channel in voice channel functionality, I don't think this feature is needed anymore. I have updated AutoRoom to handle this text channel, and have removed the automatic text channel that was being generated before.

So now all a user needs to do for a private/locked AutoRoom is use `[p]autoroom allow <botname_or_botrole>` and then they should be able to use the bots in their text channel (and voice channel). If it's a public or server room, the bots can already see those text channels so they can just be used right off the bat.

I will close this for now, feel free to comment back on this if for whatever reason you are not able to get bots working in the text channels. I tested it out, but there is always a small chance I missed something with the huge code change I did.

**Comment by hirata-estate** [comment]
-> Is there any way to make a role always have access to a **private/locked** autoroom without needing to give them the administrator permission?

Before the Discord voice/text channel update, I've had to make a hint/starting message on users' autorooms to tell them to (in-case of the Jockie music bot):
- Do !autoroom allow @Bots
- Do m!summon in a public text channel
- Then, be able to do m!play in their private text channels.
This is because even if you give the bot role permission to join the voice channel, they don't get permission to view the text channel before they join the voice channel, which leads to step #2.

This makes a lot of confusion and isn't very user friendly.

Though I still prefer the separate text channel <-> voice channel combo, it's perfectly understandable if you don't want to maintain a feature that'll be deprecated fairly soon. It would be a nice config option though if you ever want to do so. (separate-text-channel: y/n)

The 'bot-role' feature though, would still be nice not only as a fix to the issue above, but also to fix the issue of channel owners leaving, and the bots being left on the channel, keeping it alive. For example in Jockie, they have 4 separate music bots that work like copies. If 4 users were to make new channels, use the bots, and leave; there will be no more music bots freely available on the server; even though no one's using them.

**Comment by PhasecoreX** [comment]
Once discord.py (the underlying bot framework of Red-DiscordBot) allows for sending new messages into these new voice-text-channels, the text channel hints should begin working once again. I haven't removed them, they're just not visible and not able to be set. So hopefully that will help you in the future if you want a text channel hint.

With these built in text channels now, it should be less confusing as the bots can see all of the public and server AutoRooms. And with the private/locked ones, it's just one command: `[p]autoroom allow @Bots`. They can still do the summon command in their own AutoRoom text channel (instead of a public text channel) since the bots with the bots role can now see that AutoRoom.

However, I can see how having specific roles being added to all AutoRooms by default would be useful. This was almost possible just by adding the role to the AutoRoom Source, but it messes with any member roles the server might have and rely on in certain scenarios. Thus, I will reopen this in order to add a way to specify custom roles (not mod or admin) that are by default added to all AutoRooms. Unlike admin/mod roles however, these ones are still able to be manually removed by the AutoRoom Owner.

As for the 4 bots being all alone in separate rooms that are otherwise empty, I feel that's an issue with those bots. For Red-DiscordBot, you can have it so that if it's alone in a voice channel, it auto-disconnects. That's what these other bots should be doing, not relying on my cog/Red to forcibly disconnect them.

**Comment by PhasecoreX** [comment]
Okay, with https://github.com/PhasecoreX/PCXCogs/commit/353e9e3d33b5c6ce2874909da0d416cd72ecad62 I have added the command `[p]autoroomset access bot` which allows for defining a list of bot roles that will be allowed into every AutoRoom. The AutoRoom Owner is able to allow or deny these roles as well, unlike the admin and mod roles which are permanently allowed.

Hopefully this plus the comment above is sufficient!
