### ISSUE TITLE
[Bancheck] Suggestion: instructions to get the necessary API keys

### ISSUE THREAD

**Issue by HelmicNewciv** [PhasecoreX/PCXCogs#7]
Ideally it would be a link to the service's own instructions for requesting an API key, just in case they change that process on their end.  As it is, it can be a bit tricky figuring out where to get an API key for, say, Globan.

**Comment by PhasecoreX** [comment]
Well at the moment, Globan doesn't actually have a public API yet. Once that is opened up, I'll update the URL to point to it. Though due to some issues they're having on the discord server, I wouldn't hold my breath for it. Hopefully it comes out soon though.

In the case of KSoft.Si, I have it pointing to their api site, which the user would need to log into with their discord account. There isn't a page that I know of for listing out the steps for getting the API key, but I think it wasn't too hard once logged in to request the key.

**Comment by HelmicNewciv** [comment]
Ah, yeah I spent a good amount of time looking for Globan's instructions - maybe temporarily labeling it as likely not yet available (but not actually removing it as an option, in case that changes before you update the cog) could save folk some time.  For Ksoft.Si, their link is at https://api.ksoft.si/#get-started and is a bit involved.

**Comment by PhasecoreX** [comment]
Oh cool, yeah I'll update it to that link instead. It looks like all that needs to be done from that link is step 1, so maybe I'll have BanCheck mention that somewhere.

I'll also update it to show that Globan isn't available yet.

**Comment by PhasecoreX** [comment]
Okay with 64cccdc I have added some helpful hints to the supported services list. One of the commits before that I had updated the KSoft.Si link. Thanks for the suggestion!

**Comment by Kovaelin** [comment]
Dang. It'd be nice if the API keys were a bit easier to get.

**Comment by PhasecoreX** [comment]
Yeah, I agree. The KSoft.Si requires that you stay a member of their Discord server, and your bot needs to be public so they can look it over to make sure it doesn't have any TOS breaking commands. This process can take a while; for me it took like 2 weeks for them to look at and approve my bot. I guess this is the trade off that needs to be made for free access to a quality set of ban information.

I'm hoping the Globan one is easier to get an API key from. But again, they're not close to releasing a public API yet as far as I can tell.

If there are any other global ban lists, I'll be sure to implement them though!
