### ISSUE TITLE
[FEATURE][Autoroom] automatic text channels and change name of text channels

### ISSUE THREAD

**Issue by OCFormula** [PhasecoreX/PCXCogs#92]
Discord has text channels built into voice channels but it's not intuitive and it's uncomfortable so it's not used very well.

So I think the previous text channel function is better and I hope it come back.

And I wish I could change the name of the text channel separately from the voice channel.

**Comment by PhasecoreX** [comment]
The previous text channel function was borderline API abuse. It was hacked together in order to keep permissions in sync with the voice channel, all the while taking up double the number of total channels available to the server and being yet another thing for the cog to keep track of and manage. Discord's solution remedies all of this in a way I never would be able to from a cog perspective. This reduces the complexity of my cog, makes it easier to maintain, and makes it simpler for others to use my cog.

Discord's solution is quite literally "a text channel for a voice channel", which is what my feature was originally trying to solve. Thus, I will not be adding the automatic text channel feature back.
